<?php
$form = $this->form;
$tituloPainel = $this->tituloPainel;

$form->prepare();

$this->formElementErrors()->setAttributes(array('class' => 'inputError'));

?>
<div class="panel panel-primary">
	<div class="panel-heading"><h3 class="panel-title"><?php echo $this->tituloPainel ?></h3></div>
		<div class="panel-body">
			<?php echo $this->form()->openTag($form); ?>

			<?php // echo $this->formElement($form->get('security')) ?>
			
			<fieldset><legend>DADOS DO BANNER</legend></fieldset>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('idBannerTipo')); ?>
				<div class="col-md-10">
					<?php echo $this->formElement($form->get('idBannerTipo')); 
						  echo $this->formElementErrors($form->get('idBannerTipo')); ?>
				</div>
			</div>

			<div class="form-group">
				<?php echo $this->formLabel($form->get('idUsuarioConcessionaria')); ?>
				<div class="col-md-10">
					<?php echo $this->formElement($form->get('idUsuarioConcessionaria')); 
						  echo $this->formElementErrors($form->get('idUsuarioConcessionaria')); ?>
				</div>
			</div>
				  
			<fieldset><legend>BANNER</legend></fieldset>
			<div class="form-group file-upload-row">
				<?php echo $this->formLabel($form->get('caminhoBanner')); ?>
				<div class="col-md-10">
					<?php echo $this->formElement($form->get('caminhoBanner')); 
						  echo $this->formElementErrors($form->get('caminhoBanner')); ?>
				</div>
			</div>	  
			
		</div>
	<div class="panel-footer">
		<?php echo $this->formElement($form->get('submit')); ?>
	</div>
<?php echo $this->form()->closeTag(); ?>
</div>