<?php
$form = $this->form;
$tituloPainel = $this->tituloPainel;

$form->prepare();

$this->formElementErrors()->setAttributes(array('class' => 'inputError'));

?>
<div class="panel panel-primary">
	<div class="panel-heading"><h3 class="panel-title"><?php echo $this->tituloPainel ?></h3></div>
		<div class="panel-body">
			<?php echo $this->form()->openTag($form); ?>

			<?php // echo $this->formElement($form->get('security')) ?>
			
			<fieldset><legend>VEÍCULO</legend></fieldset>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('idTipoFabricante')); ?>
				<div class="col-md-10">
					<?php echo $this->formElement($form->get('idTipoFabricante')); 
						  echo $this->formElementErrors($form->get('idTipoFabricante')); ?>
				</div>
			</div>
			
			<div class="form-group">
				<?php echo $this->formLabel($form->get('nomeVeiculo')); ?>
				<div class="col-md-10">
					<?php echo $this->formElement($form->get('nomeVeiculo')); 
						  echo $this->formElementErrors($form->get('nomeVeiculo')); ?>
				</div>
			</div>
			
		</div>
	<div class="panel-footer">
		<?php echo $this->formElement($form->get('submit')); ?>
	</div>
<?php echo $this->form()->closeTag(); ?>
</div>