<div class="panel panel-primary">
	<div class="panel-heading"><h3 class="panel-title">Adicionar novo anúncio</h3></div>
	<div class="panel-body">
		<form class="form-horizontal form-backend" role="form">
			<fieldset><legend>DADOS DO CARRO</legend></fieldset>
			<div class="form-group">
				<label for="E-mail" class="col-md-2 control-label">E-mail</label>
				<div class="col-md-10">
					<input type="email" class="form-control input-large" id="email" placeholder="Email"> 
				</div>
			</div>
			<br />
			<fieldset><legend>FOTOS</legend></fieldset>
			<div class="form-group">
				<label for="E-mail" class="col-md-2 control-label">E-mail</label>
				<div class="col-md-10">
					<input type="email" class="form-control input-large" id="email" placeholder="Email"> 
				</div>
			</div>
		</form>
	</div>
	<div class="panel-footer"><button type="submit" class="btn btn-primary">Publicar anúncio ></button></div>
</div>